// programme.js — transcription fidèle du « Programme Hyrox Paris — 18 décembre 2026 ».
// Source unique du contenu des séances. Toute modification doit garder le script
// tests/fidelite.mjs à zéro écart avec tests/programme-source.md.
//
// Jetons remplacés à l'affichage (jamais d'allure seuil ou VMA écrite en dur) :
//   {seuil+0}, {seuil-3}…  allure seuil de référence décalée de n s/km (ou allure ajustée de la séance)
//   {seuil} {vma} {vma400}  allure seuil, allure VMA (seuil − 35 s/km), temps au 400 m (0,4 × VMA)
//   {S}                     taille de série wall balls
//   {ef}                    « FC sous 85 % de ta FC seuil » tant que la FC seuil n'est pas saisie, sinon « FC < X bpm »

export const TITRE = "Programme Hyrox Paris — 18 décembre 2026";
export const DEBUT = '2026-10-05';
export const DATE_COURSE = '2026-12-18';
export const OBJECTIF_DEFAUT = '1h27';
export const SEUIL_DEFAUT = 297; // 4:57/km
export const S_DEFAUT = 12;

export const PHASES = {
  reprise: { libelle: 'Reprise' },
  developpement: { libelle: 'Développement' },
  specifique: { libelle: 'Spécifique' },
  affutage: { libelle: 'Affûtage' },
};

// libelle : affiché dans l'appli ; programme : libellé de la ligne dans le détail du programme.
export const TYPES = {
  run1: { libelle: 'Cardio/run 1', programme: 'Cardio/run 1' },
  run2: { libelle: 'Cardio/run 2', programme: 'Cardio/run 2' },
  push: { libelle: 'Push' },
  pull: { libelle: 'Pull' },
  hyrox: { libelle: 'Hyrox', programme: 'Hyrox' },
  course: { libelle: 'Course', programme: 'Hyrox' },
  repos: { libelle: 'Repos' },
};

// Stations dans l'ordre officiel ; « reduit » = distances de la simulation (S8).
export const STATIONS = [
  { cle: 'ski', nom: 'SkiErg', reduit: '500 m' },
  { cle: 'sledPush', nom: 'Sled Push', reduit: '25 m' },
  { cle: 'sledPull', nom: 'Sled Pull', reduit: '25 m' },
  { cle: 'bbj', nom: 'Burpee Broad Jump', reduit: '40 m' },
  { cle: 'row', nom: 'Row', reduit: '500 m' },
  { cle: 'farmers', nom: 'Farmers Carry', reduit: '100 m' },
  { cle: 'fentes', nom: 'Sandbag Lunges', reduit: '50 m' },
  { cle: 'wb', nom: 'Wall Balls', reduit: '100 WB' },
];

// Charges Open men (extraits du paragraphe « Charges Open men » de l'objectif).
export const CHARGES = {
  sledPush: 'sled push 152 kg',
  sledPull: 'sled pull 103 kg',
  farmers: 'farmers 2 × 24 kg',
  fentes: 'sandbag 20 kg',
  wb: 'wall ball 6 kg sur cible à 3,00 m',
};
export const CHARGES_NOTE_SLED = 'traîneau compris';

// Test 2e moitié (S5) et retest (S9).
export const DEUXIEME_MOITIE = {
  segments: [
    { cle: 'r1', nom: 'Run 1' },
    { cle: 'rameur', nom: 'Rameur 1000 m' },
    { cle: 'r2', nom: 'Run 2' },
    { cle: 'farmers', nom: 'Farmers 200 m' },
    { cle: 'r3', nom: 'Run 3' },
    { cle: 'fentes', nom: 'Fentes 100 m' },
    { cle: 'r4', nom: 'Run 4' },
    { cle: 'wb', nom: '100 WB' },
  ],
  cibles: { 's5-sam': 2640, 's9-sam': 2490 }, // 44:00 et 41:30 maximum hors transitions
  bordeaux: 2870, // 47:50 hors Roxzone
};

// Allure des runs de simulation et de course (fixes, ne suivent pas le seuil).
export const ALLURE_AC = 342; // 5:42
export const ALLURE_SIMULATION = 345; // 5:45
export const R1_MAX = 345; // R1 à 5:45 maximum

// Ordre des séances seuil pour la règle de progression (la VMA de S5 n'en fait pas partie).
export const SEANCES_SEUIL = ["s3-lun","s4-lun","s6-lun","s7-lun","s8-lun","s9-lun","s10-lun"];

export const SEMAINES = [
  {
    numero: 1,
    debut: "2026-10-05",
    fin: "2026-10-11",
    dates: "5-11 oct",
    phase: "reprise",
    phaseLibelle: "Reprise",
    objectif: "Récupérer de Bordeaux, gestes propres",
    resumes: {
      run1: "30' EF dont 6 × 1' seuil",
      run2: "EF 40' + WB technique",
      hyrox: "Reprise technique",
    },
    note: null,
    jours: [
      {
        id: "s1-lun",
        date: "2026-10-05",
        jour: "lun",
        type: "run1",
        titre: "30 min EF dont 6 × 1 min seuil",
        echauffement: "les 10 premières minutes de l'EF.",
        corps: "dans les 30 min d'EF, 6 × 1 min à {seuil+0} avec 2 min d'EF entre chaque.",
        retourCalme: "5 min de marche et de mobilité.",
        duree: 40,
        dureeTexte: "≈ 40 min",
        objectif: "relancer la course après Bordeaux sans charger les jambes.",
        consigneVolume: null,
        formulaire: "standard",
        stations: [],
      },
      {
        id: "s1-mar",
        date: "2026-10-06",
        jour: "mar",
        type: "push",
        titre: "Séance Push",
        consigneVolume: null,
        formulaire: "notes",
      },
      {
        id: "s1-mer",
        date: "2026-10-07",
        jour: "mer",
        type: "run2",
        titre: "EF 40 min + WB technique",
        echauffement: "5 min de mobilité, départ très lent.",
        corps: "40 min EF à 6:00-6:20 (tu dois pouvoir parler, le test n'est pas encore fait), puis 4 × 10 WB techniques, récup 45 s.",
        retourCalme: "prévention tibias.",
        duree: 55,
        dureeTexte: "≈ 55 min",
        objectif: "base aérobie et geste propre en wall balls.",
        consigneVolume: null,
        formulaire: "standard",
        stations: ["wb"],
      },
      {
        id: "s1-jeu",
        date: "2026-10-08",
        jour: "jeu",
        type: "pull",
        titre: "Séance Pull",
        consigneVolume: null,
        formulaire: "notes",
      },
      { id: "s1-ven", date: "2026-10-09", jour: "ven", type: "repos", titre: "Repos" },
      {
        id: "s1-sam",
        date: "2026-10-10",
        jour: "sam",
        type: "hyrox",
        titre: "Reprise technique",
        echauffement: "EH.",
        corps: "jambes légères 10 min (goblet squat 3 × 10 léger, fentes à vide 2 × 10 par jambe, 2 × 15 montées sur pointes), puis 3 tours avec 2:00 de marche entre les tours : 1 km à 5:55 → 15 WB → 15 m BBJ → 20 m de fentes à 20 kg.",
        retourCalme: "RC.",
        duree: 65,
        dureeTexte: "≈ 65 min",
        objectif: "retrouver les gestes et des transitions sous 20 s, sans fatigue.",
        consigneVolume: null,
        formulaire: "hyrox",
        stations: ["bbj", "fentes", "wb"],
      },
      { id: "s1-dim", date: "2026-10-11", jour: "dim", type: "repos", titre: "Repos" },
    ],
  },
  {
    numero: 2,
    debut: "2026-10-12",
    fin: "2026-10-18",
    dates: "12-18 oct",
    phase: "developpement",
    phaseLibelle: "Développement",
    objectif: "Tests : allure seuil, FC seuil, max WB",
    resumes: { run1: "Test 30 min", run2: "EF 50' + WB", hyrox: "Test WB + BBJ/fentes" },
    note: null,
    jours: [
      {
        id: "s2-lun",
        date: "2026-10-12",
        jour: "lun",
        type: "run1",
        titre: "Test 30 min",
        echauffement: "EC.",
        corps: "test 30 min (voir Tests). Note la distance, l'allure et la FC moyenne des 20 dernières minutes.",
        retourCalme: "RC.",
        duree: 60,
        dureeTexte: "≈ 60 min",
        objectif: "fixer ton allure seuil et ta FC seuil, donc toutes les allures du plan.",
        consigneVolume: null,
        formulaire: "test30",
        stations: [],
      },
      {
        id: "s2-mar",
        date: "2026-10-13",
        jour: "mar",
        type: "push",
        titre: "Séance Push",
        consigneVolume: null,
        formulaire: "notes",
      },
      {
        id: "s2-mer",
        date: "2026-10-14",
        jour: "mer",
        type: "run2",
        titre: "EF 50 min + WB",
        echauffement: "5 min de mobilité, départ lent.",
        corps: "50 min EF ({ef}), puis 4 × 15 WB, récup 45 s.",
        retourCalme: "prévention tibias.",
        duree: 65,
        dureeTexte: "≈ 65 min",
        objectif: "première EF pilotée par la fréquence cardiaque.",
        consigneVolume: null,
        formulaire: "standard",
        stations: ["wb"],
      },
      {
        id: "s2-jeu",
        date: "2026-10-15",
        jour: "jeu",
        type: "pull",
        titre: "Séance Pull",
        consigneVolume: null,
        formulaire: "notes",
      },
      { id: "s2-ven", date: "2026-10-16", jour: "ven", type: "repos", titre: "Repos" },
      {
        id: "s2-sam",
        date: "2026-10-17",
        jour: "sam",
        type: "hyrox",
        titre: "Test WB + BBJ et fentes",
        echauffement: "EH.",
        corps: "test wall balls (max d'affilée), 3 min de récup, bloc J-dév, puis 3 tours avec 2:00 entre les tours : 1 km à 5:55 → 20 m BBJ → 25 m de fentes à 20 kg → 1 série de {S} WB.",
        retourCalme: "RC.",
        duree: 80,
        dureeTexte: "≈ 80 min",
        objectif: "fixer ta taille de série S et relancer à allure stable après les stations qui te coûtent le plus.",
        consigneVolume: null,
        formulaire: "testWB",
        stations: ["bbj", "fentes", "wb"],
      },
      { id: "s2-dim", date: "2026-10-18", jour: "dim", type: "repos", titre: "Repos" },
    ],
  },
  {
    numero: 3,
    debut: "2026-10-19",
    fin: "2026-10-25",
    dates: "19-25 oct",
    phase: "developpement",
    phaseLibelle: "Développement",
    objectif: "Seuil et force des jambes",
    resumes: { run1: "5 × 1000 m seuil", run2: "55' dont 3 × 5' AC", hyrox: "Sleds + WB fatigués" },
    note: null,
    jours: [
      {
        id: "s3-lun",
        date: "2026-10-19",
        jour: "lun",
        type: "run1",
        titre: "5 × 1000 m seuil",
        echauffement: "EC.",
        corps: "5 × 1000 m à {seuil+0}, récup 1:30 en trottinant.",
        retourCalme: "RC.",
        duree: 60,
        dureeTexte: "≈ 60 min",
        objectif: "installer l'allure seuil issue du test.",
        consigneVolume: null,
        formulaire: "seuil",
        stations: [],
        seuil: { decalage: 0, repetitions: 5 },
      },
      {
        id: "s3-mar",
        date: "2026-10-20",
        jour: "mar",
        type: "push",
        titre: "Séance Push",
        consigneVolume: null,
        formulaire: "notes",
      },
      {
        id: "s3-mer",
        date: "2026-10-21",
        jour: "mer",
        type: "run2",
        titre: "55 min dont 3 × 5 min à AC",
        echauffement: "5 min de mobilité, départ lent.",
        corps: "15 min EF, 3 × 5 min à 5:42 avec 5 min d'EF entre chaque, EF jusqu'à 55 min, puis 5 × {S} WB, récup 40 s.",
        retourCalme: "prévention tibias.",
        duree: 75,
        dureeTexte: "≈ 75 min",
        objectif: "premier contact avec l'allure de Paris, en aisance.",
        consigneVolume: null,
        formulaire: "standard",
        stations: ["wb"],
      },
      {
        id: "s3-jeu",
        date: "2026-10-22",
        jour: "jeu",
        type: "pull",
        titre: "Séance Pull",
        consigneVolume: null,
        formulaire: "notes",
      },
      { id: "s3-ven", date: "2026-10-23", jour: "ven", type: "repos", titre: "Repos" },
      {
        id: "s3-sam",
        date: "2026-10-24",
        jour: "sam",
        type: "hyrox",
        titre: "Sleds + WB fatigués",
        echauffement: "EH.",
        corps: "bloc J-dév, puis 3 tours avec 2:00 entre les tours : 1 km à 5:55 → 25 m de sled push à 152 kg → 25 m de sled pull à 103 kg. Enchaîné : 500 m de SkiErg à 2:10/500 → 60 WB en séries de {S}.",
        retourCalme: "RC.",
        duree: 85,
        dureeTexte: "≈ 85 min",
        objectif: "courir après les sleds sans exploser, et finir par des WB sur jambes chargées.",
        consigneVolume: null,
        formulaire: "hyrox",
        stations: ["ski", "sledPush", "sledPull", "wb"],
      },
      { id: "s3-dim", date: "2026-10-25", jour: "dim", type: "repos", titre: "Repos" },
    ],
  },
  {
    numero: 4,
    debut: "2026-10-26",
    fin: "2026-11-01",
    dates: "26 oct-1 nov",
    phase: "developpement",
    phaseLibelle: "Développement",
    objectif: "Densité : +1 tour, récup réduite",
    resumes: { run1: "3 × 2000 m seuil", run2: "60' dont 3 × 8' AC", hyrox: "Densité jambes 4 tours" },
    note: null,
    jours: [
      {
        id: "s4-lun",
        date: "2026-10-26",
        jour: "lun",
        type: "run1",
        titre: "3 × 2000 m seuil",
        echauffement: "EC.",
        corps: "3 × 2000 m à {seuil+0}, récup 2:00 en trottinant.",
        retourCalme: "RC.",
        duree: 65,
        dureeTexte: "≈ 65 min",
        objectif: "tenir l'allure seuil deux fois plus longtemps par répétition.",
        consigneVolume: null,
        formulaire: "seuil",
        stations: [],
        seuil: { decalage: 0, repetitions: 3 },
      },
      {
        id: "s4-mar",
        date: "2026-10-27",
        jour: "mar",
        type: "push",
        titre: "Séance Push",
        consigneVolume: null,
        formulaire: "notes",
      },
      {
        id: "s4-mer",
        date: "2026-10-28",
        jour: "mer",
        type: "run2",
        titre: "60 min dont 3 × 8 min à AC",
        echauffement: "5 min de mobilité, départ lent.",
        corps: "15 min EF, 3 × 8 min à 5:42 avec 3 min d'EF entre chaque, EF jusqu'à 60 min, puis 6 × {S} WB, récup 40 s.",
        retourCalme: "prévention tibias.",
        duree: 80,
        dureeTexte: "≈ 80 min",
        objectif: "allonger les blocs à l'allure de Paris.",
        consigneVolume: null,
        formulaire: "standard",
        stations: ["wb"],
      },
      {
        id: "s4-jeu",
        date: "2026-10-29",
        jour: "jeu",
        type: "pull",
        titre: "Séance Pull",
        consigneVolume: null,
        formulaire: "notes",
      },
      { id: "s4-ven", date: "2026-10-30", jour: "ven", type: "repos", titre: "Repos" },
      {
        id: "s4-sam",
        date: "2026-10-31",
        jour: "sam",
        type: "hyrox",
        titre: "Densité jambes, 4 tours",
        echauffement: "EH.",
        corps: "bloc J-dév, puis 4 tours avec 1:30 entre les tours : 1 km à 5:50 → 20 m BBJ → 25 m de fentes à 20 kg → {S} WB.",
        retourCalme: "RC.",
        duree: 85,
        dureeTexte: "≈ 85 min",
        objectif: "par rapport à la semaine 2, +1 tour, −30 s de récup et −5 s/km en course.",
        consigneVolume: null,
        formulaire: "hyrox",
        stations: ["bbj", "fentes", "wb"],
      },
      { id: "s4-dim", date: "2026-11-01", jour: "dim", type: "repos", titre: "Repos" },
    ],
  },
  {
    numero: 5,
    debut: "2026-11-02",
    fin: "2026-11-08",
    dates: "2-8 nov",
    phase: "developpement",
    phaseLibelle: "Développement (assimilation)",
    objectif: "Volume −30 %, test de référence",
    resumes: { run1: "10 × 400 m VMA", run2: "EF 45' + WB", hyrox: "Test 2e moitié" },
    note: null,
    jours: [
      {
        id: "s5-lun",
        date: "2026-11-02",
        jour: "lun",
        type: "run1",
        titre: "10 × 400 m VMA",
        echauffement: "EC.",
        corps: "10 × 400 m en {vma400}, récup 1:15 en trottinant.",
        retourCalme: "RC.",
        duree: 60,
        dureeTexte: "≈ 60 min",
        objectif: "garder du rythme avec un volume réduit d'environ 30 %.",
        consigneVolume: null,
        formulaire: "standard",
        stations: [],
      },
      {
        id: "s5-mar",
        date: "2026-11-03",
        jour: "mar",
        type: "push",
        titre: "Séance Push",
        consigneVolume: "volume −30 %",
        formulaire: "notes",
      },
      {
        id: "s5-mer",
        date: "2026-11-04",
        jour: "mer",
        type: "run2",
        titre: "EF 45 min + WB",
        echauffement: "5 min de mobilité, départ lent.",
        corps: "45 min EF, puis 4 × {S} WB, récup 45 s.",
        retourCalme: "prévention tibias.",
        duree: 60,
        dureeTexte: "≈ 60 min",
        objectif: "récupérer en gardant la fréquence en wall balls.",
        consigneVolume: null,
        formulaire: "standard",
        stations: ["wb"],
      },
      {
        id: "s5-jeu",
        date: "2026-11-05",
        jour: "jeu",
        type: "pull",
        titre: "Séance Pull",
        consigneVolume: "volume −30 %",
        formulaire: "notes",
      },
      { id: "s5-ven", date: "2026-11-06", jour: "ven", type: "repos", titre: "Repos" },
      {
        id: "s5-sam",
        date: "2026-11-07",
        jour: "sam",
        type: "hyrox",
        titre: "Test 2e moitié de course",
        echauffement: "EH, puis 2 × 200 m progressifs.",
        corps: "enchaîné dans l'ordre de course, 1 km → 1000 m de rameur → 1 km → 200 m de farmers à 2 × 24 kg → 1 km → 100 m de fentes à 20 kg → 1 km → 100 WB. Course le plus vite tenable, en visant 5:50. Chronomètre chaque segment et teste ton plan de boisson (gorgées après le rameur et après les fentes). Repère Bordeaux sur cette portion : 47:50 hors Roxzone, mais tu y arrivais déjà fatigué. Cible : 44:00 maximum hors transitions.",
        retourCalme: "RC.",
        duree: 75,
        dureeTexte: "≈ 75 min",
        objectif: "poser ta référence sur la partie de course qui concentre tes points faibles ; tu la refais en semaine 9.",
        consigneVolume: null,
        formulaire: "moitie",
        stations: ["row", "farmers", "fentes", "wb"],
      },
      { id: "s5-dim", date: "2026-11-08", jour: "dim", type: "repos", titre: "Repos" },
    ],
  },
  {
    numero: 6,
    debut: "2026-11-09",
    fin: "2026-11-15",
    dates: "9-15 nov",
    phase: "specifique",
    phaseLibelle: "Spécifique",
    objectif: "Allure cible dès la sortie de station",
    resumes: { run1: "4 × 1600 m seuil", run2: "65' dont 2 × 12' AC", hyrox: "Station → run" },
    note: null,
    jours: [
      {
        id: "s6-lun",
        date: "2026-11-09",
        jour: "lun",
        type: "run1",
        titre: "4 × 1600 m seuil",
        echauffement: "EC.",
        corps: "4 × 1600 m à {seuil-3}, récup 1:30.",
        retourCalme: "RC.",
        duree: 65,
        dureeTexte: "≈ 65 min",
        objectif: "seuil plus rapide de 3 s/km sur des répétitions plus longues.",
        consigneVolume: null,
        formulaire: "seuil",
        stations: [],
        seuil: { decalage: -3, repetitions: 4 },
      },
      {
        id: "s6-mar",
        date: "2026-11-10",
        jour: "mar",
        type: "push",
        titre: "Séance Push",
        consigneVolume: null,
        formulaire: "notes",
      },
      {
        id: "s6-mer",
        date: "2026-11-11",
        jour: "mer",
        type: "run2",
        titre: "65 min dont 2 × 12 min à AC",
        echauffement: "5 min de mobilité, départ lent.",
        corps: "15 min EF, 2 × 12 min à 5:42 avec 4 min d'EF entre les deux, EF jusqu'à 65 min, puis 6 × {S} WB, récup 30 s.",
        retourCalme: "prévention tibias.",
        duree: 85,
        dureeTexte: "≈ 85 min",
        objectif: "tenir l'allure cible 12 min sans dérive.",
        consigneVolume: null,
        formulaire: "standard",
        stations: ["wb"],
      },
      {
        id: "s6-jeu",
        date: "2026-11-12",
        jour: "jeu",
        type: "pull",
        titre: "Séance Pull",
        consigneVolume: null,
        formulaire: "notes",
      },
      { id: "s6-ven", date: "2026-11-13", jour: "ven", type: "repos", titre: "Repos" },
      {
        id: "s6-sam",
        date: "2026-11-14",
        jour: "sam",
        type: "hyrox",
        titre: "Station → run",
        echauffement: "EH.",
        corps: "bloc J-spé, puis 4 blocs avec 2:00 de marche entre les blocs : 40 m BBJ → 1 km ; 50 m de sled push → 1 km ; 50 m de fentes à 20 kg → 1 km ; 50 WB en séries de {S} → 1 km. Course à 5:45, les 200 premiers mètres tolérés à 5:55.",
        retourCalme: "RC.",
        duree: 80,
        dureeTexte: "≈ 80 min",
        objectif: "retrouver l'allure cible dès la sortie de station, là où tes tours R3 à R5 étaient 49 à 72 s plus lents que R2.",
        consigneVolume: null,
        formulaire: "hyrox",
        stations: ["sledPush", "bbj", "fentes", "wb"],
      },
      { id: "s6-dim", date: "2026-11-15", jour: "dim", type: "repos", titre: "Repos" },
    ],
  },
  {
    numero: 7,
    debut: "2026-11-16",
    fin: "2026-11-22",
    dates: "16-22 nov",
    phase: "specifique",
    phaseLibelle: "Spécifique",
    objectif: "Densité fentes + WB",
    resumes: { run1: "2 × 3000 m seuil", run2: "65' dont 3 × 10' AC", hyrox: "Fentes + WB en densité" },
    note: null,
    jours: [
      {
        id: "s7-lun",
        date: "2026-11-16",
        jour: "lun",
        type: "run1",
        titre: "2 × 3000 m seuil",
        echauffement: "EC.",
        corps: "2 × 3000 m à {seuil-3}, récup 2:30.",
        retourCalme: "RC.",
        duree: 65,
        dureeTexte: "≈ 65 min",
        objectif: "seuil continu long, dernier gros bloc avant la simulation.",
        consigneVolume: null,
        formulaire: "seuil",
        stations: [],
        seuil: { decalage: -3, repetitions: 2 },
      },
      {
        id: "s7-mar",
        date: "2026-11-17",
        jour: "mar",
        type: "push",
        titre: "Séance Push",
        consigneVolume: null,
        formulaire: "notes",
      },
      {
        id: "s7-mer",
        date: "2026-11-18",
        jour: "mer",
        type: "run2",
        titre: "65 min dont 3 × 10 min à AC",
        echauffement: "5 min de mobilité, départ lent.",
        corps: "15 min EF, 3 × 10 min à 5:42 avec 3 min d'EF entre chaque, EF jusqu'à 65 min, puis 7 × {S} WB, récup 30 s.",
        retourCalme: "prévention tibias.",
        duree: 85,
        dureeTexte: "≈ 85 min",
        objectif: "30 min cumulées à l'allure de Paris.",
        consigneVolume: null,
        formulaire: "standard",
        stations: ["wb"],
      },
      {
        id: "s7-jeu",
        date: "2026-11-19",
        jour: "jeu",
        type: "pull",
        titre: "Séance Pull",
        consigneVolume: null,
        formulaire: "notes",
      },
      { id: "s7-ven", date: "2026-11-20", jour: "ven", type: "repos", titre: "Repos" },
      {
        id: "s7-sam",
        date: "2026-11-21",
        jour: "sam",
        type: "hyrox",
        titre: "Fentes + WB en densité",
        echauffement: "EH.",
        corps: "bloc J-court, puis 3 tours avec 1:30 entre les tours : 1 km à 5:45 → 50 m de fentes à 20 kg → 1 km à 5:45 → 40 WB en séries de {S}.",
        retourCalme: "RC.",
        duree: 85,
        dureeTexte: "≈ 85 min",
        objectif: "enchaîner tes deux pires stations avec de la course entre elles, à allure cible.",
        consigneVolume: null,
        formulaire: "hyrox",
        stations: ["fentes", "wb"],
      },
      { id: "s7-dim", date: "2026-11-22", jour: "dim", type: "repos", titre: "Repos" },
    ],
  },
  {
    numero: 8,
    debut: "2026-11-23",
    fin: "2026-11-29",
    dates: "23-29 nov",
    phase: "specifique",
    phaseLibelle: "Spécifique",
    objectif: "Valider le plan d'allure et la nutrition",
    resumes: { run1: "6 × 1000 m seuil", run2: "55' dont 10' AC", hyrox: "Simulation complète" },
    note: null,
    jours: [
      {
        id: "s8-lun",
        date: "2026-11-23",
        jour: "lun",
        type: "run1",
        titre: "6 × 1000 m seuil",
        echauffement: "EC.",
        corps: "6 × 1000 m à {seuil-5}, récup 1:15.",
        retourCalme: "RC.",
        duree: 65,
        dureeTexte: "≈ 65 min",
        objectif: "la séance seuil la plus rapide du cycle.",
        consigneVolume: null,
        formulaire: "seuil",
        stations: [],
        seuil: { decalage: -5, repetitions: 6 },
      },
      {
        id: "s8-mar",
        date: "2026-11-24",
        jour: "mar",
        type: "push",
        titre: "Séance Push",
        consigneVolume: null,
        formulaire: "notes",
      },
      {
        id: "s8-mer",
        date: "2026-11-25",
        jour: "mer",
        type: "run2",
        titre: "55 min dont 10 min à AC",
        echauffement: "5 min de mobilité, départ lent.",
        corps: "20 min EF, 10 min à 5:42, 25 min EF, puis 4 × {S} WB, récup 40 s.",
        retourCalme: "prévention tibias.",
        duree: 70,
        dureeTexte: "≈ 70 min",
        objectif: "volume contenu pour arriver frais à la simulation.",
        consigneVolume: null,
        formulaire: "standard",
        stations: ["wb"],
      },
      {
        id: "s8-jeu",
        date: "2026-11-26",
        jour: "jeu",
        type: "pull",
        titre: "Séance Pull",
        consigneVolume: null,
        formulaire: "notes",
      },
      { id: "s8-ven", date: "2026-11-27", jour: "ven", type: "repos", titre: "Repos" },
      {
        id: "s8-sam",
        date: "2026-11-28",
        jour: "sam",
        type: "hyrox",
        titre: "Simulation complète, à 9h si possible",
        echauffement: "EH, puis 2 × 100 m progressifs.",
        corps: "8 × 1 km à 5:45 et les 8 stations dans l'ordre officiel, charges Open. Distances réduites pour tenir en 1h30, sauf les wall balls : 500 m de SkiErg, 25 m de push, 25 m de pull, 40 m de BBJ, 500 m de rameur, 100 m de farmers, 50 m de fentes, 100 WB. Transitions de 20 s maximum. Petit-déjeuner et boisson exactement comme le jour J. Cible : course à 5:45 sans dérive de R5 à R8, WB en 7:15 maximum.",
        retourCalme: "5 min de marche.",
        duree: 90,
        dureeTexte: "≈ 1h30",
        objectif: "valider ton plan d'allure et ta nutrition à 20 jours de la course. Si tu peux t'accorder 2h ce jour-là, fais les stations en distance complète : c'est la seule séance où ça vaut le coup de dépasser 1h30.",
        consigneVolume: null,
        formulaire: "simulation",
        stations: ["ski", "sledPush", "sledPull", "bbj", "row", "farmers", "fentes", "wb"],
      },
      { id: "s8-dim", date: "2026-11-29", jour: "dim", type: "repos", titre: "Repos" },
    ],
  },
  {
    numero: 9,
    debut: "2026-11-30",
    fin: "2026-12-06",
    dates: "30 nov-6 déc",
    phase: "specifique",
    phaseLibelle: "Spécifique (pic)",
    objectif: "Dernière semaine dure",
    resumes: { run1: "5 × 1000 m seuil", run2: "70' dont 25' AC", hyrox: "Retest 2e moitié" },
    note: null,
    jours: [
      {
        id: "s9-lun",
        date: "2026-11-30",
        jour: "lun",
        type: "run1",
        titre: "5 × 1000 m seuil",
        echauffement: "EC.",
        corps: "5 × 1000 m à {seuil-2}, récup 1:30. Si tes jambes sont encore lourdes de la simulation, fais-en 4.",
        retourCalme: "RC.",
        duree: 60,
        dureeTexte: "≈ 60 min",
        objectif: "garder l'intensité sans empiler la fatigue de la simulation.",
        consigneVolume: null,
        formulaire: "seuil",
        stations: [],
        seuil: { decalage: -2, repetitions: 5 },
      },
      {
        id: "s9-mar",
        date: "2026-12-01",
        jour: "mar",
        type: "push",
        titre: "Séance Push",
        consigneVolume: null,
        formulaire: "notes",
      },
      {
        id: "s9-mer",
        date: "2026-12-02",
        jour: "mer",
        type: "run2",
        titre: "70 min dont 25 min continues à AC",
        echauffement: "5 min de mobilité, départ lent.",
        corps: "20 min EF, 25 min à 5:42, 25 min EF, puis 8 × {S} WB, récup 25 s.",
        retourCalme: "prévention tibias.",
        duree: 90,
        dureeTexte: "≈ 90 min",
        objectif: "pic de volume, avec 25 min d'allure cible d'une traite.",
        consigneVolume: null,
        formulaire: "standard",
        stations: ["wb"],
      },
      {
        id: "s9-jeu",
        date: "2026-12-03",
        jour: "jeu",
        type: "pull",
        titre: "Séance Pull",
        consigneVolume: null,
        formulaire: "notes",
      },
      { id: "s9-ven", date: "2026-12-04", jour: "ven", type: "repos", titre: "Repos" },
      {
        id: "s9-sam",
        date: "2026-12-05",
        jour: "sam",
        type: "hyrox",
        titre: "Retest 2e moitié à allure cible",
        echauffement: "EH.",
        corps: "pré-fatigue, 1 km à 5:45 → 40 m de BBJ, puis 2:00 de récup. Enchaîné : 1 km → 1000 m de rameur → 1 km → 200 m de farmers → 1 km → 100 m de fentes → 1 km → 100 WB. Course à 5:42, stations aux temps cibles. Cible : 41:30 maximum hors transitions (contre 44:00 maximum en semaine 5).",
        retourCalme: "RC.",
        duree: 80,
        dureeTexte: "≈ 80 min",
        objectif: "mesurer ta progression sur tes points faibles en partant pré-fatigué, et trancher l'objectif final avec la règle de révision.",
        consigneVolume: null,
        formulaire: "retest",
        stations: ["bbj", "row", "farmers", "fentes", "wb"],
      },
      { id: "s9-dim", date: "2026-12-06", jour: "dim", type: "repos", titre: "Repos" },
    ],
  },
  {
    numero: 10,
    debut: "2026-12-07",
    fin: "2026-12-13",
    dates: "7-13 déc",
    phase: "affutage",
    phaseLibelle: "Affûtage",
    objectif: "Semaine allégée (−40 %)",
    resumes: { run1: "4 × 1000 m seuil", run2: "EF 45' dont 2 × 6' AC", hyrox: "Rappel d'allure" },
    note: null,
    jours: [
      {
        id: "s10-lun",
        date: "2026-12-07",
        jour: "lun",
        type: "run1",
        titre: "4 × 1000 m seuil",
        echauffement: "EC.",
        corps: "4 × 1000 m à {seuil-2}, récup 2:00.",
        retourCalme: "RC.",
        duree: 55,
        dureeTexte: "≈ 55 min",
        objectif: "garder l'intensité en coupant le volume d'environ 40 %.",
        consigneVolume: null,
        formulaire: "seuil",
        stations: [],
        seuil: { decalage: -2, repetitions: 4 },
      },
      {
        id: "s10-mar",
        date: "2026-12-08",
        jour: "mar",
        type: "push",
        titre: "Séance Push",
        consigneVolume: "volume −40 %",
        formulaire: "notes",
      },
      {
        id: "s10-mer",
        date: "2026-12-09",
        jour: "mer",
        type: "run2",
        titre: "EF 45 min dont 2 × 6 min à AC",
        echauffement: "5 min de mobilité, départ lent.",
        corps: "15 min EF, 2 × 6 min à 5:42 avec 3 min d'EF entre les deux, EF jusqu'à 45 min, puis 3 × {S} WB, récup 45 s.",
        retourCalme: "prévention tibias.",
        duree: 60,
        dureeTexte: "≈ 60 min",
        objectif: "entretenir les sensations d'allure sans fatigue.",
        consigneVolume: null,
        formulaire: "standard",
        stations: ["wb"],
      },
      {
        id: "s10-jeu",
        date: "2026-12-10",
        jour: "jeu",
        type: "pull",
        titre: "Séance Pull",
        consigneVolume: "volume −40 %",
        formulaire: "notes",
      },
      { id: "s10-ven", date: "2026-12-11", jour: "ven", type: "repos", titre: "Repos" },
      {
        id: "s10-sam",
        date: "2026-12-12",
        jour: "sam",
        type: "hyrox",
        titre: "Rappel d'allure",
        echauffement: "EH.",
        corps: "bloc J-court (version S10), 500 m de rameur et 500 m de SkiErg à 2:10/500, puis 3 tours avec 2:30 entre les tours : 1 km à 5:42 → 25 m de push et 25 m de pull ; 1 km → 40 m de BBJ ; 1 km → 50 WB.",
        retourCalme: "RC.",
        duree: 70,
        dureeTexte: "≈ 70 min",
        objectif: "répéter les gestes à allure de course avec moitié moins de volume.",
        consigneVolume: null,
        formulaire: "hyrox",
        stations: ["ski", "sledPush", "sledPull", "bbj", "row", "wb"],
      },
      { id: "s10-dim", date: "2026-12-13", jour: "dim", type: "repos", titre: "Repos" },
    ],
  },
  {
    numero: 11,
    debut: "2026-12-14",
    fin: "2026-12-18",
    dates: "14-18 déc",
    phase: "affutage",
    phaseLibelle: "Affûtage",
    objectif: "Course vendredi à 9h",
    resumes: { run1: "3 × 1000 m AC", run2: "Déblocage 20' (jeudi)", hyrox: "COURSE" },
    note: "Pull avancé au mercredi et Run 2 au jeudi, pour finir la veille de la course.",
    jours: [
      {
        id: "s11-lun",
        date: "2026-12-14",
        jour: "lun",
        type: "run1",
        titre: "3 × 1000 m à AC",
        echauffement: "15 min EF et 4 lignes droites.",
        corps: "3 × 1000 m à 5:42, récup 1:30, puis 4 × 150 m relâchés.",
        retourCalme: "5 min de marche.",
        duree: 45,
        dureeTexte: "≈ 45 min",
        objectif: "ancrer ton allure de départ.",
        consigneVolume: null,
        formulaire: "standard",
        stations: [],
      },
      {
        id: "s11-mar",
        date: "2026-12-15",
        jour: "mar",
        type: "push",
        titre: "Séance Push",
        consigneVolume: "mi-volume",
        formulaire: "notes",
      },
      {
        id: "s11-mer",
        date: "2026-12-16",
        jour: "mer",
        type: "pull",
        titre: "Séance Pull",
        consigneVolume: "mi-volume",
        formulaire: "notes",
      },
      {
        id: "s11-jeu",
        date: "2026-12-17",
        jour: "jeu",
        type: "run2",
        titre: "Déblocage, à 9h si possible",
        echauffement: "aucun en plus.",
        corps: "15 min EF, 4 lignes droites de 80 m, 10 WB légers.",
        retourCalme: "5 min de marche.",
        duree: 25,
        dureeTexte: "≈ 25 min",
        objectif: "arriver frais sans perdre le rythme.",
        consigneVolume: null,
        formulaire: "standard",
        stations: ["wb"],
      },
      {
        id: "s11-ven",
        date: "2026-12-18",
        jour: "ven",
        type: "course",
        titre: "COURSE, Hyrox Paris Open men à 9h",
        echauffement: "15 min dans la demi-heure avant ton départ (5 min de footing, mobilité, 2 × 100 m progressifs, 5 WB).",
        corps: "R1 à 5:45 maximum, puis 5:42 ; stations aux temps cibles ; transitions de 20 s maximum ; WB en séries de {S} ; quelques gorgées à chaque point d'eau dès le R3.",
        retourCalme: "10 min de marche et réhydratation.",
        duree: 87,
        dureeTexte: "≈ 1h27",
        objectif: "1h27.",
        consigneVolume: null,
        formulaire: "course",
        stations: ["ski", "sledPush", "sledPull", "bbj", "row", "farmers", "fentes", "wb"],
      },
    ],
  },
];

export const SECTIONS = [
  {
    niveau: 2,
    id: "objectif",
    titre: "Objectif : 1h27 le vendredi 18 décembre à 9h",
    blocs: [
      {
        type: "p",
        id: "cible",
        texte: "Cible : 1h27 en Open men, soit 9 min de moins qu'à Bordeaux (1:35:57). 1h15 reste hors de portée en 11 semaines : il faudrait courir tes 8 km autour de 4:55/km sous fatigue.",
      },
      {
        type: "p",
        id: "r1",
        texte: "Ton R1 de Bordeaux (3:18) faisait probablement moins d'un km. À tracé complet, ta course vaudrait plutôt ~1h38, donc la vraie marche à franchir est d'environ 11 min.",
      },
      {
        type: "table",
        id: "temps-cibles",
        entetes: ["Segment", "Bordeaux", "Cible Paris"],
        lignes: [
          {
            id: "course",
            cellules: ["Course (moyenne R2-R8)", "6:18/km", "5:42/km (8 × 5:42 = 45:36)"],
            bordeaux: 378,
            cible: 342,
          },
          { id: "ski", cellules: ["SkiErg","4:24","4:20"], bordeaux: 264, cible: 260 },
          { id: "sledPush", cellules: ["Sled Push","3:38","3:15"], bordeaux: 218, cible: 195 },
          { id: "sledPull", cellules: ["Sled Pull","4:55","4:25"], bordeaux: 295, cible: 265 },
          { id: "bbj", cellules: ["Burpee Broad Jump","6:18","5:15"], bordeaux: 378, cible: 315 },
          { id: "row", cellules: ["Row","4:26","4:20"], bordeaux: 266, cible: 260 },
          { id: "farmers", cellules: ["Farmers Carry","2:13","2:00"], bordeaux: 133, cible: 120 },
          { id: "fentes", cellules: ["Sandbag Lunges","6:09","5:00"], bordeaux: 369, cible: 300 },
          { id: "wb", cellules: ["Wall Balls","9:31","7:15"], bordeaux: 571, cible: 435 },
          { id: "roxzone", cellules: ["Roxzone","7:08","5:30"], bordeaux: 428, cible: 330 },
          { id: "total", cellules: ["Total","1:35:57","≈ 1:27"], bordeaux: 5757, cible: 5220 },
        ],
      },
      {
        type: "p",
        id: "revision",
        texte: "Règle de révision après le retest de la semaine 9 : 2e moitié bouclée en 40:30 ou moins → vise 1h25 ; au-delà de 43:00 → vise 1h29-1h30.",
      },
      {
        type: "p",
        id: "charges",
        texte: "Charges Open men, identiques à Bordeaux : sled push 152 kg et sled pull 103 kg traîneau compris, farmers 2 × 24 kg, sandbag 20 kg, wall ball 6 kg sur cible à 3,00 m. Ta salle est sur moquette comme en course : tes temps de sled y sont comparables.",
      },
    ],
  },
  {
    niveau: 2,
    id: "diagnostic",
    titre: "Partie 1 — Diagnostic",
    blocs: [
      {
        type: "p",
        texte: "Point faible 1 — Course sous fatigue. À frais tu cours 7 km à 4:54/km en contrôle, mais tes tours Hyrox R2-R8 font 6:18 de moyenne : tu perds ~1:24/km là où un athlète bien préparé perd plutôt 30 à 60 s (ordre de grandeur). Tes pires tours suivent les sleds et le BBJ (R3-R5, 49 à 72 s plus lents que R2), et passer à 5:42 de moyenne vaut ~5 min.",
      },
      {
        type: "p",
        texte: "Point faible 2 — Fentes + BBJ : 12:27 cumulés (122e et 111e du groupe d'âge). Aux fentes ce sont tes jambes qui lâchent, au BBJ ton cardio, et ta muscu actuelle compte moins de 10 % de travail de jambes et aucune fente. Écart avec la cible : ~2:10.",
      },
      {
        type: "p",
        texte: "Point faible 3 — Wall Balls : 9:31 (108e). C'est 23 % de ton temps en stations, à 5,7 s par répétition : tu perds le temps dans les pauses, juste après une crampe au dernier run. Écart avec la cible : ~2:15.",
      },
      {
        type: "p",
        texte: "Point fort 1 — Rameur : 4:26, 15e du groupe d'âge, 100 places au-dessus de ton classement général.",
      },
      {
        type: "p",
        texte: "Point fort 2 — SkiErg : 4:24, 37e, à entretenir sans y investir de temps.",
      },
    ],
  },
  {
    niveau: 2,
    id: "vue-ensemble",
    titre: "Partie 2 — Vue d'ensemble",
    blocs: [
      {
        type: "p",
        id: "intro",
        texte: "11 semaines du lundi 5 octobre au vendredi 18 décembre, en 4 phases : reprise (S1), développement (S2-S5), spécifique (S6-S9) et affûtage (S10-S11).",
      },
      {
        type: "table",
        id: "semaine-type",
        entetes: ["Lun", "Mar", "Mer", "Jeu", "Ven", "Sam", "Dim"],
        lignes: [
          {
            cellules: ["Cardio/run 1 (qualité)", "Push", "Cardio/run 2 (endurance)", "Pull", "Repos", "Hyrox", "Repos"],
          },
        ],
      },
      {
        type: "ul",
        items: [
          {
            id: "48h",
            texte: "Le Hyrox du samedi et le run qualité du lundi sont toujours séparés par au moins 48 h.",
          },
          {
            id: "vendredi",
            texte: "Le vendredi off te fait arriver frais à la séance clé. Fais le Hyrox du samedi à 9h quand tu peux : c'est ton heure de départ.",
          },
          {
            id: "s11",
            texte: "Semaine 11 : Pull le mercredi et Run 2 le jeudi, pour finir la veille de la course.",
          },
          {
            id: "volume",
            texte: "Volume de course stable autour de 25-30 km par semaine : tu es déjà à 30 km, la progression passe par la qualité et la course sous fatigue.",
          },
        ],
      },
      {
        type: "semaines",
        entetes: ["Sem.", "Dates", "Phase", "Objectif de la semaine", "Cardio/run 1", "Cardio/run 2", "Séance Hyrox"],
      },
    ],
  },
  {
    niveau: 2,
    id: "reperes",
    titre: "Partie 3 — Repères pour toutes les séances",
    blocs: [],
  },
  {
    niveau: 3,
    id: "allures",
    titre: "Allures",
    blocs: [
      {
        type: "p",
        id: "intro",
        texte: "Les allures partent de ton 7 km à 4:54 « contrôlé avec peu de marge » et de tes tours Hyrox ; le test de la semaine 2 les fixe définitivement.",
      },
      {
        type: "table",
        id: "allures",
        entetes: ["Repère", "Valeur par défaut", "Ce qui la fixe"],
        lignes: [
          { id: "SL", cellules: ["Seuil (SL)","{seuil}/km","Test 30 min, S2"] },
          { id: "VMA", cellules: ["VMA courte","{vma}/km (400 m en {vma400})","Seuil − 35 s/km"] },
          { id: "AC", cellules: ["AC (allure cible Paris)","5:42/km","Objectif 1h27"] },
          { id: "EF", cellules: ["EF","{ef} (≈ 5:55-6:20/km)","Test 30 min, S2"] },
          {
            id: "runs-hyrox",
            cellules: ["Runs des séances Hyrox", "5:55 (S1-S3), 5:50 (S4-S5), 5:45 (S6-S8), 5:42 (S9-S10)", "Progression vers l'AC"],
          },
        ],
      },
      {
        type: "ul",
        items: [
          {
            id: "decalage",
            texte: "Si ton test donne un seuil différent de 4:57, décale le seuil et la VMA du même écart dans tout le plan. L'AC ne bouge pas avant la semaine 9.",
          },
          {
            id: "ef-note",
            texte: "Ton EF sera sans doute plus lente que tes footings habituels (5:30-5:55) : c'est voulu, la FC décide.",
          },
          {
            id: "progression",
            texte: "Séance seuil finie en pouvant faire 2 répétitions de plus → −5 s/km la semaine suivante. Allure lâchée sur les 2 dernières → tu la gardes une semaine de plus.",
          },
          {
            id: "helio",
            texte: "Je ne connais pas la précision de la Helio Strap en fractionné : si la courbe montre des pics aberrants, fie-toi à l'allure. Synchronise-la avec Strava pour garder la FC dans tes exports.",
          },
        ],
      },
    ],
  },
  {
    niveau: 3,
    id: "tests",
    titre: "Tests",
    blocs: [
      {
        type: "ul",
        items: [
          {
            id: "test30",
            texte: "Test 30 min (S2, lundi). Protocole de Joe Friel : une estimation de terrain, pas une mesure de labo. Cours 30 min seul, le plus vite possible à effort régulier, sur piste ou tapis à 1 %, et appuie sur « tour » à 10 min. FC moyenne et allure moyenne des 20 dernières minutes = ta FC seuil et ton allure seuil.",
          },
          {
            id: "testWB",
            texte: "Test wall balls (S2, samedi). Maximum d'affilée à frais (6 kg, cible à 3 m, no-reps non comptés). Ta taille de série S = la moitié de ce max (règle empirique ; 12 si tu ne fais pas le test).",
          },
        ],
      },
    ],
  },
  {
    niveau: 3,
    id: "standards",
    titre: "Standards",
    blocs: [
      {
        type: "ul",
        items: [
          {
            id: "EC",
            texte: "EC, échauffement course (20 min) : 12 min EF, 5 min de gammes (montées de genoux, talons-fesses, pas chassés), 4 × 80 m progressifs.",
          },
          {
            id: "EH",
            texte: "EH, échauffement Hyrox (12 min) : 4 min de rameur facile, 4 min EF, 2 min de mobilité hanches, chevilles et épaules, puis 1 tour léger (8 WB, 10 m BBJ, 10 fentes à vide).",
          },
          {
            id: "RC",
            texte: "RC, retour au calme (8-10 min) : EF ou marche, puis 2 min de mobilité.",
          },
          {
            id: "tibias",
            texte: "Prévention tibias (5 min, fin de chaque Run 2) : 2 × 15 relevés de pointe de pied dos au mur et 2 × 15 montées sur pointes. Ta cadence est à ~145-150 pas/min : vise ~155 en EF sans allonger la foulée. C'est une piste de prévention, pas une obligation.",
          },
        ],
      },
    ],
  },
  {
    niveau: 3,
    id: "jambes",
    titre: "Blocs jambes (dans les séances Hyrox)",
    blocs: [
      {
        type: "ul",
        items: [
          {
            id: "J-dév",
            texte: "J-dév (S2-S4, 18 min). A : back squat 4 × 6 à RPE 8 (2 répétitions en réserve), en alternance avec 4 × 12 montées sur pointes, récup 90 s. B : fentes bulgares 3 × 8 par jambe avec haltères, en alternance avec soulevé de terre roumain 3 × 8, récup 60 s.",
          },
          {
            id: "J-spé",
            texte: "J-spé (S6, 15 min). Back squat 3 × 5 à RPE 8, puis fentes marchées 3 × 20 m avec deux kettlebells de 20 kg en rack, récup 60 s.",
          },
          {
            id: "J-court",
            texte: "J-court (S7 et S10, 8 min). Back squat 3 × 5 à RPE 7. En S10 : 2 × 5 à RPE 6, puis 2 × 20 m de fentes à 20 kg.",
          },
          {
            id: "sans-bloc",
            texte: "Pas de bloc en S5, S8 et S9 : les tests et la simulation font le travail.",
          },
        ],
      },
    ],
  },
  {
    niveau: 3,
    id: "consignes",
    titre: "Consignes permanentes en séance Hyrox",
    blocs: [
      {
        type: "ul",
        items: [
          {
            id: "transitions",
            texte: "Transitions chronométrées, 20 s maximum. Repars en trottinant dès que tu poses, surtout aux sorties qui t'ont coûté le plus à Bordeaux (BBJ 0:50, Sled Push 0:46, Row 0:45).",
          },
          { id: "series-WB", texte: "Wall balls en séries de {S}, pauses de 10 s maximum." },
          {
            id: "charges-seance",
            texte: "Charges Open men, 1h30 maximum par séance, échauffement et retour au calme compris.",
          },
        ],
      },
    ],
  },
  {
    niveau: 3,
    id: "hydratation",
    titre: "Hydratation, sommeil, alcool",
    blocs: [
      {
        type: "ul",
        items: [
          {
            id: "crampes",
            texte: "Crampes. La fatigue des jambes en est souvent la cause principale, la déshydratation joue aussi : le travail de jambes est ta vraie correction. Dans toute séance de plus de 60 min, bois 500 à 750 ml par heure avec électrolytes, en petites gorgées dès le début.",
          },
          {
            id: "sommeil",
            texte: "Sommeil. Vise 8 h (tu es à 7 h), surtout les veilles du lundi et du samedi.",
          },
          {
            id: "alcool",
            texte: "Alcool. Zéro la veille des séances clés (dimanche et vendredi soir) et zéro à partir du 8 décembre : c'est ce qui a fait dérailler ta fin de prépa à Bordeaux.",
          },
        ],
      },
    ],
  },
  { niveau: 2, id: "detail", titre: "Détail séance par séance", blocs: [{"type":"detail"}] },
  {
    niveau: 2,
    id: "semaine-course",
    titre: "Partie 4 — Semaine de course",
    blocs: [
      {
        type: "ul",
        items: [
          {
            id: "mar",
            texte: "Mar 15 : Push à mi-volume ; zéro alcool depuis le 8 décembre.",
            jour: "s11-mar",
          },
          {
            id: "mer",
            texte: "Mer 16 : Pull à mi-volume, rien de lourd ; plus de glucides à chaque repas, coucher tôt.",
            jour: "s11-mer",
          },
          {
            id: "jeu",
            texte: "Jeu 17 : déblocage de 20 min à 9h, puis retrait du dossard si possible et repérage de la Roxzone et des points d'eau.",
            jour: "s11-jeu",
          },
          {
            id: "jeu-soir",
            texte: "Jeu soir : dîner riche en glucides, rien de nouveau ; sac prêt, plan relu (R1 à 5:45 maximum, séries de {S}, transitions de 20 s maximum).",
            jour: "s11-jeu",
          },
          {
            id: "ven",
            texte: "Ven 18 : réveil vers 5h45, petit-déjeuner testé lors de la simulation vers 6h, 500 ml d'eau avec électrolytes dans les 2 h avant le départ.",
            jour: "s11-ven",
          },
        ],
      },
    ],
  },
  {
    niveau: 2,
    id: "sources",
    titre: "Sources",
    blocs: [
      {
        type: "ul",
        items: [
          {
            id: "dates",
            texte: "Fitness Park HYROX Paris, saison 26/27 (https://france.hyrox.com/event/hyrox-paris-season-26-27-hfkuj6) : dates de course (12-13 et 16-20 décembre 2026).",
          },
          {
            id: "charges",
            texte: "HYROX Weights by Division (https://rundida.com/tools/hyrox-weights/) : charges Open men d'après le règlement Singles 26/27.",
          },
        ],
      },
    ],
  },
];

// Définitions dépliables : chaque référence pointe vers un texte du programme (section:id).
export const GLOSSAIRE = {
  EC: { nom: 'Échauffement course', refs: ['standards:EC'] },
  EH: { nom: 'Échauffement Hyrox', refs: ['standards:EH'] },
  RC: { nom: 'Retour au calme', refs: ['standards:RC'] },
  'prévention tibias': { nom: 'Prévention tibias', refs: ['standards:tibias'] },
  'J-dév': { nom: 'Bloc jambes J-dév', refs: ['jambes:J-dév'] },
  'J-spé': { nom: 'Bloc jambes J-spé', refs: ['jambes:J-spé'] },
  'J-court': { nom: 'Bloc jambes J-court', refs: ['jambes:J-court'] },
  EF: { nom: 'Endurance fondamentale', refs: ['allures:EF', 'allures:ef-note'] },
  AC: { nom: 'Allure cible Paris', refs: ['allures:AC', 'allures:decalage'] },
  SL: { nom: 'Seuil', refs: ['allures:SL', 'allures:decalage', 'allures:progression'] },
  VMA: { nom: 'VMA courte', refs: ['allures:VMA'] },
  WB: { nom: 'Wall balls', refs: ['charge:wb', 'consignes:series-WB'] },
  BBJ: { nom: 'Burpee Broad Jump', refs: ['temps-cibles:bbj'] },
  S: { nom: 'Taille de série wall balls', refs: ['tests:testWB'] },
};
